export const itemClasses = [
    'Consumable',
    'Container',
    'Weapon',
    'Gem',
    'Armor',
    'Reagent',
    'Projectile',
    'Tradegoods',
    'ItemEnhancement',
    'Recipe',
    'CurrencyTokenObsolete',
    'Quiver',
    'Questitem',
    'Key',
    'PermanentObsolete',
    'Miscellaneous',
    'Glyph',
    'Battlepet',
    'WoWToken',
    'Profession',
];

export const itemSubTypes = {
    Weapon: [
        'Axe 1H',
        'Axe 2H',
        'Bows',
        'Guns',
        'Mace 1H',
        'Mace 2H',
        'Polearm',
        'Sword 1H',
        'Sword 2H',
        'Warglaive',
        'Staff',
        'Bearclaw',
        'Catclaw',
        'Unarmed',
        'Generic',
        'Dagger',
        'Thrown',
        'Obsolete3',
        'Crossbow',
        'Wand',
        'Fishingpole',
    ],
    Armor: ['Misc', 'Cloth', 'Leather', 'Mail', 'Plate', 'Cosmetic', 'Shield'],
    Reagent: ['Reagent', 'Keystone', 'ContextToken'],
    Miscellaneous: [
        'Junk',
        'Reagent',
        'CompanionPet',
        'Holiday',
        'Other',
        'Mount',
        'MountEquipment',
    ],
};
