CREATE TYPE "source" AS ENUM (
  'original',
  'token',
  'catalyst'
);

CREATE TABLE "items" (
  "id" int PRIMARY KEY,
  "name" text,
  "icon" text,
  "type" text,
  "subtype" text
);

CREATE TABLE "encounters" (
  "id" int PRIMARY KEY,
  "instance_id" int,
  "name" text,
  "icon" text
);

CREATE TABLE "instances" (
  "id" int PRIMARY KEY,
  "name" text,
  "description" text
);

CREATE TABLE "reports" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" text UNIQUE,
  "char_id" int,
  "spec_id" int,
  "difficulty" text,
  "instance_id" int,
  "dps" float,
  "date" date,
  "avg_ilvl" float,
  "avg_ilvl_equip" float,
  "upgrade_path" text,
  "upgrade_level" int,
  "upgrade_max" int
);

CREATE TABLE "characters" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "server" text NOT NULL,
  "class" text
);

CREATE TABLE "specs" (
  "id" int PRIMARY KEY,
  "name" text,
  "icon" text
);

CREATE TABLE "spec_instances" (
  "spec_id" int,
  "instance_id" int,
  PRIMARY KEY ("spec_id", "instance_id")
);

CREATE TABLE "report_items" (
  "report_id" int,
  "item_id" int,
  "slot" text,
  "encounter_id" int,
  "ilvl" int,
  "source" source,
  "dps" float,
  PRIMARY KEY ("report_id", "item_id", "slot", "encounter_id", "ilvl", "source")
);

CREATE UNIQUE INDEX ON "reports" ("char_id", "spec_id", "difficulty", "instance_id");

CREATE UNIQUE INDEX ON "characters" ("name", "server");

ALTER TABLE "encounters" ADD FOREIGN KEY ("instance_id") REFERENCES "instances" ("id");

ALTER TABLE "reports" ADD FOREIGN KEY ("char_id") REFERENCES "characters" ("id");

ALTER TABLE "reports" ADD FOREIGN KEY ("spec_id") REFERENCES "specs" ("id");

ALTER TABLE "reports" ADD FOREIGN KEY ("instance_id") REFERENCES "instances" ("id");

ALTER TABLE "spec_instances" ADD FOREIGN KEY ("spec_id") REFERENCES "specs" ("id");

ALTER TABLE "spec_instances" ADD FOREIGN KEY ("instance_id") REFERENCES "instances" ("id");

ALTER TABLE "report_items" ADD FOREIGN KEY ("report_id") REFERENCES "reports" ("id");

ALTER TABLE "report_items" ADD FOREIGN KEY ("item_id") REFERENCES "items" ("id");

ALTER TABLE "report_items" ADD FOREIGN KEY ("encounter_id") REFERENCES "encounters" ("id");
